version: "2"
services:
  web:
    build: ./app
    ports:
      - "8080:8080"
    volumes:
      - /home/alemasar/Projects/express-server/express-server/app:/app:rw
    environment:
      - NODE_ENV=development
    networks:
      - frontend
networks:
  frontend:
    # Use a custom driver
    driver: bridge